// Copies what the Next app needs from this Hardhat project:
//   ../lib/chain/abis.ts          typed ABIs (as const, for viem)
//   ../lib/chain/deployments.json deployed addresses per chain id
// Run after `hardhat build` and after every deployment: npm run export-app
import { existsSync, readFileSync, readdirSync, writeFileSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const appChainDir = path.join(root, "..", "lib", "chain");

const CONTRACTS = {
  registryAbi: "CinovaRegistry",
  vaultAbi: "CinovaVault",
  subscriptionsAbi: "CinovaSubscriptions",
  tipsAbi: "CinovaTips",
  backerPassAbi: "BackerPass",
  campaignFactoryAbi: "CampaignFactory",
  filmCampaignAbi: "FilmCampaign",
  // The testnet token: an ERC-20 plus owner-only mint.
  tokenAbi: "CinovaTestUSD",
};

const abi = (name) =>
  JSON.parse(readFileSync(path.join(root, "artifacts", "contracts", `${name}.sol`, `${name}.json`), "utf8")).abi;

let out = "// Generated by contracts/scripts/export-to-app.mjs — do not edit by hand.\n\n";
for (const [exportName, contract] of Object.entries(CONTRACTS)) {
  out += `export const ${exportName} = ${JSON.stringify(abi(contract))} as const;\n\n`;
}
writeFileSync(path.join(appChainDir, "abis.ts"), out);

// Ignition future ids look like "CinovaTestnet#CinovaVault".
const KEYS = {
  CinovaRegistry: "registry",
  CinovaVault: "vault",
  CinovaSubscriptions: "subscriptions",
  CinovaTips: "tips",
  BackerPass: "backerPass",
  CampaignFactory: "campaignFactory",
  MockUSDC: "token",
  CinovaTestUSD: "token",
};
const deploymentsDir = path.join(root, "ignition", "deployments");
const deployments = {};
if (existsSync(deploymentsDir)) {
  for (const dir of readdirSync(deploymentsDir)) {
    const match = dir.match(/^chain-(\d+)$/);
    const file = path.join(deploymentsDir, dir, "deployed_addresses.json");
    if (!match || !existsSync(file)) continue;
    const addresses = {};
    for (const [futureId, address] of Object.entries(JSON.parse(readFileSync(file, "utf8")))) {
      const key = KEYS[futureId.split("#")[1]];
      if (key) addresses[key] = address;
    }
    deployments[match[1]] = addresses;
  }
}
writeFileSync(path.join(appChainDir, "deployments.json"), JSON.stringify(deployments, null, 2) + "\n");
console.log(`Exported ${Object.keys(CONTRACTS).length} ABIs and deployments for chains: ${Object.keys(deployments).join(", ") || "none yet"}`);
